name: Deployment using GitHub Pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deployment:
    name: Deploying to www.lesleyvaden.dev

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - name: Clean install dependencies
        run: npm ci

      - name: Deploy www.lesleyvaden.dev
        run: |
          git config user.name "lesley-byte" && git config user.email "phosphorescence3@hotmail.com"
          npm run deploy
